### ISSUE TITLE
Case Sensitivity

### ISSUE THREAD

**Issue by 9072997** [martinlindhe/base36#8]
Base36 is often used in instances where the case of the encoded text may not be preserved. This library does not correctly decode lower case strings.

https://go.dev/play/p/K2kNMutrI4L
```go
encoded := base36.EncodeBytes([]byte("Hello World"))
fmt.Printf("encoded: %s\n", encoded)

decoded := base36.DecodeToBytes(encoded)
fmt.Printf("decoded: %s\n", decoded)

encodedLowerCase := strings.ToLower(encoded)
fmt.Printf("encodedLowerCase: %s\n", encodedLowerCase)

decoded = base36.DecodeToBytes(encodedLowerCase)
fmt.Printf("decoded: %s\n", decoded)
```
```txt
encoded: AZW5BZ2XP56M4QYCK
decoded: Hello World
encodedLowerCase: azw5bz2xp56m4qyck
decoded: 
```

**Comment by martinlindhe** [comment]
Base36 is an algorithm to encode numbers as a short-form. The function EncodeBytes() does not take any byte sequence, but is supposed to be used for encoding numbers up to 64 bits.

**Comment by martinlindhe** [comment]
Thanks for the report!

The DecodeToBytes() indeed had a issue with lowercase input.
I fixed it with a sledgehammer now,  but the code needs a cleanup someday, since half of it got rewritten a while back.

I would have preferred to clean up DecodeToBytes() to also use the uint8Index instead, but I'm out of time!

**Comment by 9072997** [comment]
Wow. You've got a better response time than most of the vendors we pay. Thanks for the fix.
